name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/deps/submodules
    - name: Setup External 
      uses: ./.github/actions/deps/external
    - name: Mpy Cross
      uses: ./.github/actions/mpy_cross


    - name: Run distcheck
      run: make fetch-tags
    - name: Run sqlite
      run: make -C ports/unix USER_C_MODULES=examples/usercmodule && ports/unix/micropython < ports/unix/usqlite_test.py
      
